# Production environment override
services:
  php:
    image: jcsmithf22/time-manager:latest
    build:
      context: .
      target: frankenphp_prod
      platforms:
        - "linux/amd64"
    environment:
      APP_SECRET: ${APP_SECRET}
      # APP_DEBUG: 0
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

